version: "3"
services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    #volumes:
    #  - "${HOME}/neo4j/data:/data"

  cwfparser:
    build: .
    command: ["./wait-for-it.sh", "neo4j:7474", "--", "python", "app.py"]